apiVersion: victor.test/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  schedule: "*/1 * * * *" # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-container
            image: busybox
            command: ["echo", "Hello from the ClusterScan job!"]
          restartPolicy: Never